CREATE DATABASE IF NOT EXISTS pos_artha26;

USE pos_artha26;

CREATE TABLE IF NOT EXISTS transaksi (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pendapatan DECIMAL(10,2) DEFAULT 0,
  keuntungan DECIMAL(10,2) DEFAULT 0,
  pengeluaran DECIMAL(10,2) DEFAULT 0,
  deskripsi VARCHAR(255),
  tanggal TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS produk (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(255) NOT NULL,
  harga DECIMAL(10,2) NOT NULL,
  stok INT DEFAULT 0,
  deskripsi TEXT,
  gambar VARCHAR(500),
  kategori VARCHAR(50) DEFAULT 'food',
  tanggal TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  tanggal TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);